# Generated by Django 2.2.1 on 2019-06-01 14:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0002_auto_20190601_1424")]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="iatiorganisation",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        )
    ]
