# Generated by Django 2.2.1 on 2019-06-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0003_auto_20190601_1424")]

    operations = [
        migrations.RemoveField(model_name="activity", name="id"),
        migrations.AddField(
            model_name="activity",
            name="identifier",
            field=models.TextField(default="a", primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
