# Generated by Django 2.2.2 on 2019-06-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0007_codelist_codelistitem")]

    operations = [
        migrations.AddField(
            model_name="codelistitem",
            name="codelist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="iati_fetch.Codelist",
            ),
            preserve_default=False,
        )
    ]
