# Generated by Django 2.2.2 on 2019-07-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0010_organisationabbreviation")]

    operations = [
        migrations.DeleteModel(name="OrganisationAbbreviation"),
        migrations.RemoveField(model_name="organisation", name="abbreviation"),
    ]
