# Generated by Django 2.2.2 on 2019-07-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0012_organisationabbreviation")]

    operations = [migrations.DeleteModel(name="OrganisationAbbreviation")]
