# Generated by Django 2.2.2 on 2019-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0013_delete_organisationabbreviation")]

    operations = [
        migrations.CreateModel(
            name="OrganisationAbbreviation",
            fields=[
                ("abbreviation", models.TextField(primary_key=True, serialize=False))
            ],
        )
    ]
