# Generated by Django 2.2.2 on 2019-07-02 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0014_organisationabbreviation")]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="abbreviation",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="iati_fetch.OrganisationAbbreviation",
            ),
            preserve_default=False,
        )
    ]
