# Generated by Django 2.2.2 on 2019-07-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0015_organisation_abbreviation")]

    operations = [
        migrations.AddField(
            model_name="organisationabbreviation",
            name="withdrawn",
            field=models.BooleanField(default=False),
        )
    ]
