# Generated by Django 2.2.3 on 2019-07-03 14:10

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0017_requestcacherecord_exception")]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element",
                    django.contrib.postgres.fields.jsonb.JSONField(db_index=True),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iati_fetch.Activity",
                    ),
                ),
            ],
        )
    ]
