# Generated by Django 2.2.3 on 2019-07-03 14:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0018_transaction")]

    operations = [
        migrations.RemoveField(model_name="transaction", name="element"),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
