# Generated by Django 2.2.3 on 2019-07-03 14:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0019_auto_20190703_1439")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="element",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="ref",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
