# Generated by Django 2.2.3 on 2019-07-03 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0020_auto_20190703_1441")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="description",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="title",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="element",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, db_index=True, null=True
            ),
        ),
    ]
