# Generated by Django 2.2.3 on 2019-07-03 15:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0021_auto_20190703_1511")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="narrative",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
