# Generated by Django 2.2.3 on 2019-07-03 15:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("iati_fetch", "0022_activity_narrative")]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="element",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
